### ISSUE TITLE
Errors because of quoted hex string

### ISSUE THREAD

**Issue by fidian** [jakwings/bash-totp#1]
I tried this script and received an error.

    # ./totp "$MFA_SECRET"
    ./totp: line 56: ("0x466d0ab5" & 0x7FFFFFFF) % 1000000 : syntax error: operand expected (error token is ""0x466d0ab5" & 0x7FFFFFFF) % 1000000 ")

On line 56, you are doing some math like this.

    # echo $(( (0x466d0ab5 & 0x7FFFFFFF) % 1000000 ))
    551285

However, when you add the quotes (like the script currently has), you get the problem.

    # echo $(( ("0x466d0ab5" & 0x7FFFFFFF) % 1000000 ))
    -bash: ("0x466d0ab5" & 0x7FFFFFFF) % 1000000 : syntax error: operand expected (error token is ""0x466d0ab5" & 0x7FFFFFFF) % 1000000 ")

What do you think? Should the quotes be removed, or were you considering putting the hex code into a variable and then putting the variable into the expression?

For reference, I am using CentOS 6 and the following version of Bash.

    # bash --version
    GNU bash, version 4.1.2(2)-release (x86_64-redhat-linux-gnu)
    Copyright (C) 2009 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

    This is free software; you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

**Comment by iology** [comment]
Thank you. Should be fixed now. Apparently this is another caveat of the old design of bash.
